### ISSUE TITLE
Problem retrieving some metadata

### ISSUE THREAD

**Issue by Sergenansen** [alan-morey/force-meta-backup#17]
Hi,

I'm using you tool to do some backup on SF orgs, but I noticed this mornin that it doesn't retrieve some metadata such as 'Apexclass'
In order to have comparison, I made retrieves from one same org with 'force-meta-backup' and with Eclipse using 'force.com migration tool'
Here are screenshots
![eclipse](https://cloud.githubusercontent.com/assets/6783481/2892827/a4972cc8-d541-11e3-8e63-b5f525307cac.png)

![explorer](https://cloud.githubusercontent.com/assets/6783481/2892836/b3d24a2e-d541-11e3-8065-db3b293393e7.png)

in eclipse : 61 items
in force-meta-backup: 37 items

groovy version: 2.2.2 JVM: 1.7.0_51 Oracle : Windows 7
Apache Ant(TM) version 1.9.3 compiled on December 23 2013

Thank you

**Comment by dosmakov** [comment]
It is very old open issue May 6, 2014. I met simultaneous issue, but with different Salesforce.com User Profiles. I found out that it is impossible to retrieve ApexClasses if "Author Apex" checkbox is not ticked. I am not sure but maybe it will useful information.

**Comment by alan-morey** [comment]
@dosmakov Thanks for the information, I always run my backups as an Administrator, so this would explain why I've never encountered this issue. I'll make a note in README that backups should be performed as an Administrator, to ensure correct access for retrieving components.
