### ISSUE TITLE
Attribute 'metadataType' cannot be an empty string

### ISSUE THREAD

**Issue by thomasdziedzic** [alan-morey/force-meta-backup#42]
When I run `ant backupMetadata` I get the following:

```BUILD FAILED
/Users/thomas/Downloads/force-meta-backup-1.35.1/build.xml:42: The following error occurred while executing this line:
/Users/thomas/Downloads/force-meta-backup-1.35.1/build/folders-build.xml:132: Attribute 'metadataType' cannot be an empty string```

indeed, this is a snippet of folders-build.xml:

```    <sf:bulkRetrieve metadataType='' containingFolder='SharedApp' retrieveTarget='${build.metadata.dir}' username='${sf.username}' password='${sf.password}' serverurl='${sf.serverurl}' pollWaitMillis='${sf.pollWaitMillis}' maxPoll='${sf.maxPoll}' />
  </target>
</project>```

According to my logs, this has been failing since 3/19/2016

**Comment by alan-morey** [comment]
Can you check the details of that folder in your Org:

```sql
SELECT Id, Name, DeveloperName, AccessType, IsReadonly, Type, NamespacePrefix
FROM Folder
WHERE DeveloperName = 'SharedApp'
```

The `metadataType` attribute should be populated based on the value of `Type` field, which should be one of:

- Dashboard
- Document
- Email
- Report

Is the `Type` field populated?

**Comment by thomasdziedzic** [comment]
It looks like it is populated, this is what I get when I run the query:

![screen shot 2016-04-15 at 2 21 14 pm](https://cloud.githubusercontent.com/assets/203340/14575234/5ef64b82-0315-11e6-8174-68087ab153d1.png)

**Comment by alan-morey** [comment]
Ah the `Type` is **Insights**, was not expecting that.

It's not documented in SOAP or Metadata API.

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_folder.htm
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm

Not sure, how this should be handled. Seeing as the `AccessType` is `Hidden` maybe this folder should ignored from backup?

Are there any other `Type`s in your Org other that `Insights` and the expected 4?

**Comment by alan-morey** [comment]
Maybe mapping the folder `Type` to one of the Metadata Types would work.

You could trying modifiying `force-meta-backup.groovy` and changing the `folderMetaTypeByFolderType` variable in [force-meta-backup.groovy#L339](https://github.com/alan-morey/force-meta-backup/blob/337389d5986a6aae3a9ee0127aa108cd056bc802/force-meta-backup.groovy#L339) as follows:

```
def folderMetaTypeByFolderType = [
        Dashboard: 'Dashboard',
        Document: 'Document',
        Email: 'EmailTemplate',
        Report: 'Report',
        Insights: 'Report'
]
```

**Comment by thomasdziedzic** [comment]
> Are there any other Types in your Org other than Insights and the expected 4?

No

**Comment by thomasdziedzic** [comment]
> You could trying modifiying force-meta-backup.groovy and changing the folderMetaTypeByFolderType variable in force-meta-backup.groovy#L339 as follows:

This worked
