### ISSUE TITLE
No signature of method: static java.net.URLEncoder.encode() is applicable for argument types: (groovy.util.ConfigObject, java.lang.String)

### ISSUE THREAD

**Issue by rjpalomboFiserv** [alan-morey/force-meta-backup#50]
generatePackageXmlAndBuildXml:
     [exec] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     [exec] SLF4J: Defaulting to no-operation (NOP) logger implementation
     [exec] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
     [exec] Caught: groovy.lang.MissingMethodException: No signature of method: static java.net.URLEncoder.encode() is applicable for argument types: (groovy.util.ConfigObject, java.lang
     [exec] Possible solutions: encode(java.lang.String), encode(java.lang.String, java.lang.String), hashCode()
     [exec] groovy.lang.MissingMethodException: No signature of method: static java.net.URLEncoder.encode() is applicable for argument types: (groovy.util.ConfigObject, java.lang.String)
     [exec] Possible solutions: encode(java.lang.String), encode(java.lang.String, java.lang.String), hashCode()
     [exec]     at java_net_URLEncoder$encode.call(Unknown Source)
     [exec]     at ForceService$_closure1$_closure6.doCall(force-meta-backup.groovy:184)
     [exec]     at ForceService$_closure1$_closure7.doCall(force-meta-backup.groovy:190)
     [exec]     at ForceService$_closure1.doCall(force-meta-backup.groovy:187)
     [exec]     at ForceService.<init>(force-meta-backup.groovy:29)
     [exec]     at ForceServiceFactory.create(force-meta-backup.groovy:211)
     [exec]     at ForceServiceFactory$create.call(Unknown Source)
     [exec]     at force-meta-backup.run(force-meta-backup.groovy:926)

BUILD FAILED
C:\force-meta-backup\build.xml:34: The following error occurred while executing this line:
C:\force-meta-backup\build.xml:23: exec returned: 1

Total time: 5 seconds

**Comment by alan-morey** [comment]
What version JDK and Groovy are you using?

**Comment by rjpalomboFiserv** [comment]
javac 1.8.0_121
Groovy Version: 2.4.9 JVM: 1.8.0_121

**Comment by rjpalomboFiserv** [comment]
This was all a fault of invalid build.properties on my part

**Comment by alan-morey** [comment]
@rjpalomboFiserv In case others run into the same issue, can you share what specifically was the fault in your `build.properties`?

**Comment by rjpalomboFiserv** [comment]
Sure. My issue was rather noob, I hate to say it. We use a deviation from the default sf. properties for each org. For example we use sf.uat-username. Since -uat wasn't in the build.xml it crashed.
